name: modapi
version: 1.0
api-version: 1.18
author: WillM
main: com.willm.CoreMOD.Main
comments: Make sure to remove this YML, only use files in com.willm.ModAPI! Run the ModAPI.Main.Launch() function in your onEnable function. (COPY THE COMMANDS TO YOUR .yml)
commands:
   removebrokenstand:
      description: Removes all nearby armorstands.
   givecustom:
      aliases: [ gc ]
      description: Gives you a custom item.
   enchantcustom:
      description: Enchants the held item with the specified custom enchantment.
   itemmenu:
      aliases: [ im, creativemenu ]
      description: Opens a creative menu of custom items.
   assortedtool:
      description: Allows the creation of an alloyed tool.